# Generated by Django 5.2.3 on 2025-08-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
