# Generated by Django 5.2.3 on 2025-08-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='raiting',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
