# Generated by Django 5.2.3 on 2025-08-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogentry_raiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogentry',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='blogentry',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
