# Generated by Django 5.2.3 on 2025-09-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blogentry_user_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
