# Generated by Django 5.2.3 on 2025-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True),
        ),
    ]
