# Generated by Django 5.2.3 on 2025-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blogentry_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpost',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
