# Generated by Django 5.2.3 on 2025-09-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_savedpost_category_savedpost_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='note',
        ),
        migrations.AddField(
            model_name='blogentry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog_videos/'),
        ),
    ]
